apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: patient-central-dev
  name: jmeter-master
  labels:
    jmeter_mode: master
spec:
  replicas: 1
  selector:
    matchLabels:
      jmeter_mode: master
  template:
    metadata:
      labels:
        jmeter_mode: master
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: jmmaster
        image: rbillon59/jmeter-k8s-base:5.4.1
        imagePullPolicy: Always
        env:
        - name: MODE
          value: "MASTER"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command: ["/bin/bash"]
        args: ["-c", "trap 'exit 0' SIGUSR1 && until [ -f /opt/jmeter/load_test ]; do sleep 5; done && /bin/bash /opt/jmeter/load_test"]
        ports:
        - containerPort: 60000
        resources:
          requests:
            memory: 8Gi
            cpu: 8000m
          limits:
            memory: 16Gi
            cpu: 12000m
        livenessProbe:
          exec:
            command:
            - cat
            - /opt/jmeter/apache-jmeter/bin/jmeter
          initialDelaySeconds: 5
          periodSeconds: 5
